name: ci-deploy
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: 16

      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      # 运行构建脚本
      - name: Build VitePress site
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: gh-pages
          jekyll: false
          build_dir: .vitepress/dist
        env:
          GH_PAT: ${{ secrets.DEPLOY_GH }} 
